CREATE DATABASE IF NOT EXISTS photoapp;
USE photoapp;

CREATE TABLE IF NOT EXISTS users (
    user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    post_id VARCHAR(25) NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    image_file VARCHAR(255) NOT NULL UNIQUE,
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INT REFERENCES users(user_id)
);